---
title: "Spokane Crime - Exploring Data"
author: "Patil"
date: "September 26, 2016"
output: html_document
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Reading data

```{r}
# Arrive at Crime_byNeighborhood using earlier code that was originated by Krisztian
# crimedfonly=data.frame(Crime_byNeighborhood)
# save(crimedfonly,file="Data/Crime_byNeighborhood.Rda")

load("Data/Crime_byNeighborhood.Rda")
str(crimedfonly)
```

# Calling on a few packages

```{r}
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(lubridate))
library(leaflet)
library(ggmap)

```

# Total offenses

```{r}
crimedfonly %>% group_by(OFFGEN)%>%summarise(Counts=length(OFFGEN))%>% ggplot(.,aes(reorder(OFFGEN,Counts),Counts))+geom_bar(stat="identity")+geom_text(aes(x=OFFGEN,y=Counts+2000,label=Counts))+coord_flip()+theme_bw()+labs(y="Count",x="")

```

# Number of times offenses occured in different neighborhoods

```{r}

crimedfonly %>% group_by(Name)%>%summarise(Counts=length(Name))%>%filter(Name!="")%>% ggplot(.,aes(reorder(Name,Counts),Counts))+geom_bar(stat="identity")+geom_text(aes(x=Name,y=Counts+1000,label=Counts))+coord_flip()+theme_bw()+labs(y="Count",x="")
```

## Offenses in different neighborhoods

```{r fig.width=10, fig.height=6}
# A shiny app will do well here

crimedfonly %>% group_by(Name,OFFGEN)%>%summarise(Counts=length(OFFGEN))%>%filter(Name!="")%>% ggplot(.,aes(OFFGEN,Counts))+geom_bar(stat="identity")+facet_wrap(~Name,scales="free")

```

## Messing with Dates

```{r}
# Adds 9 columns to the dataset

crimedfonly=crimedfonly[,1:11]

# Beginning dates parsed

crimedfonly$beginyear=year(ymd(crimedfonly$BEGINDATE))
crimedfonly$beginmonth=month(ymd(crimedfonly$BEGINDATE),label=TRUE)# label parameter inserts name of month instead of number
crimedfonly$begindate=day(ymd(crimedfonly$BEGINDATE)) 
crimedfonly$beginday=wday(ymd(crimedfonly$BEGINDATE)) # label parameter inserts day of week instead of number of the day in a 7-day week

# Ending dates parsed

crimedfonly$endyear=year(ymd(crimedfonly$ENDDATE))
crimedfonly$endmonth=month(ymd(crimedfonly$ENDDATE),label=TRUE)
crimedfonly$enddate=day(ymd(crimedfonly$ENDDATE))
crimedfonly$endday=wday(ymd(crimedfonly$ENDDATE),label=TRUE)

# duration, in days, between starting and ending days
crimedfonly$durationdays= (as.duration(ymd(crimedfonly$ENDDATE)-ymd(crimedfonly$BEGINDATE)))/ddays(1)

head(crimedfonly)

```

```{r eval=FALSE}
crimedfonly=crimedfonly[!is.na(crimedfonly$Lat),]
crimedfonly=crimedfonly[!is.na(crimedfonly$Lng),]
crime2008=crimedfonly[crimedfonly$beginyear==2008,]

location=c(-117.402209,47.665330)
map=get_map(location,source="osm", color="bw",zoom=11)

for (i in 1:10){

  
crimedfsub=crimedfonly[crimedfonly$OFFGEN==levels(crimedfonly$OFFGEN)[i],]
ggmap(map)+geom_point(data=crimedfsub,aes(Lng,Lat),color="red")+facet_wrap(~beginyear)+theme(panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                axis.text = element_blank(),axis.title = element_blank(),
                axis.ticks = element_blank())+ggtitle(paste(levels(crimedfonly$OFFGEN)[i],"Over the Years"))

ggsave(file=paste("annualplot",i,".png",sep=""),scale=4)
}
                                                      
```





```{r eval=FALSE}
pal <- colorFactor(rainbow(10), domain = levels(crime2008$OFFGEN))
crimedfonly=crimedfonly[!is.na(crimedfonly$Lat),]
crimedfonly=crimedfonly[!is.na(crimedfonly$Lng),]
crime2008=crimedfonly[crimedfonly$beginyear==2008,]
levels(crime2008$OFFGEN)
leaflet(data=crime2008)%>%addTiles()%>%addCircleMarkers(color =~pal(OFFGEN),popup=~LOCATION)
```



# Few low hanging fruits to pick next



* plots of trends for years, months, weeks, days, offense types
* mapping stuff by different variables


